# GitHub action to build LAMMPS on Linux and run standard unit tests
name: "Unittest for Linux /w -DFFT_SINGLE=ON"

on:
  push:
    branches:
      - develop
      - maintenance
  pull_request:
    branches:
      - develop

  workflow_dispatch:

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  build:
    name: Linux Unit Test
    if: ${{ github.repository == 'lammps/lammps' }}
    runs-on: ubuntu-latest
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 2

    - name: Install extra packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ccache \
                                libeigen3-dev \
                                libcurl4-openssl-dev \
                                mold \
                                ninja-build \
                                python3-dev

    - name: Create Build Environment
      run: mkdir build

    - name: Set up ccache
      uses: actions/cache@v4
      with:
        path: ${{ env.CCACHE_DIR }}
        key: linux-unit-ccache-${{ github.sha }}
        restore-keys: linux-unit-ccache-

    - name: Building LAMMPS via CMake
      shell: bash
      run: |
        ccache -z
        python3 -m venv linuxenv
        source linuxenv/bin/activate
        python3 -m pip install numpy
        python3 -m pip install pyyaml
        cmake -S cmake -B build \
              -C cmake/presets/gcc.cmake \
              -C cmake/presets/most.cmake \
              -C cmake/presets/nolib.cmake \
              -D CMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -D CMAKE_C_COMPILER_LAUNCHER=ccache \
              -D BUILD_SHARED_LIBS=on \
              -D FFT=kiss \
              -D FFT_SINGLE=on \
              -D DOWNLOAD_POTENTIALS=off \
              -D ENABLE_TESTING=on \
              -D MLIAP_ENABLE_PYTHON=off \
              -G Ninja
        cmake --build build
        ccache -s

    - name: Run Tests
      working-directory: build
      shell: bash
      run: ctest -V
